### ISSUE TITLE
git ll fails with less than 3 commits

### ISSUE THREAD

**Issue by m-wynn** [phy1729/dotfiles#1]
Attempting to use `git ll` on a repository with less than 3 commits fails with the message:

```
fatal: ambiguous argument 'master~3': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

This appears to be caused by b3e1bd0 and appears on [.gitconfig:23](https://github.com/phy1729/dotfiles/blob/master/.gitconfig#L23).

Of course, one could simply use `git lga` but it would be better for `lga` to be called automagically if `ll` fails.

**Comment by the-maldridge** [comment]
I am also affected by this issue, using git 2.6.3 on Void Linux (x86_64) please fix as soon as possible.

**Comment by bhomer7** [comment]
Same error on OSX Yosemite. Please fix as soon as possible.

**Comment by adesca** [comment]
Using Git 2.6.3 on CVOS, this does not appear to work. Please fix, this is breaking my workflow.

**Comment by Vaelatern** [comment]
Trying this triggered a wipe of an audio CD in my optical drive. Pls fix.

**Comment by the-maldridge** [comment]
Anyone heard from the original author?  Is this abandonware?

**Comment by phy1729** [comment]
This of course also happens on projects just as Ansible that have chosen to not have a master branch.

The user of these dotfiles is expected to exercise some common sense. The the settings in ~/.gitconfig are intended to be sane defaults and overridden at a repository level when necessary.

Closing as won't fix for now; however, a pull request would be considered.
